---
# kustomize/development/dind-cache-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-cache
spec:
  storageClassName: "longhorn"
  accessModes:
    # Note this is only for local K8S because longhorn does not support ROX
    # See: https://github.com/longhorn/longhorn/issues/5041
    - ReadWriteMany
